### PR TITLE
Turn the notes into a textbook (v2.0)

### LINKED ISSUE #1: Turning this into a book
We (me and @birocoles) have plans of turning this into a book. The general idea is to have a short, direct, example driven book. This means adding lots of code to the current text we have.

We also want to make the text and code freely available on the internet (probably under a Creative Commons license). [Recommended read: [Textbook Manifesto](http://greenteapress.com/wp/textbook-manifesto/)]

Some options for writing the actual book:
1. Use **Jupyter notebooks** for everything.
   
   Advantages:
   - The text and code will be together and the reader can execute the code without copy pasting.
   - Can easily insert images and interactive widgets
   - Can execute online (no installing necessary) on http://mybinder.org/
   - Can export notebooks to PDF and HTML with a bit of effort using `jupyter nbconvert`
   
   Disadvantages:
   - No referencing support (no Bibtex or Latex `\cite` commands)
   - No numbering of equations
   - No good way of testing the output of the code (like doctests)
   - Terrible diff/merge so not good for developing using Github PRs.
2. Use **Latex** for the text and **notebooks** for the code
   
   Advantages:
   - All the benefits of writing in Latex
   - Executing code still in notebook form
   - Can use PRs to develop the text
   
   Disadvantages:
   - Bad export of text to HTML
   - Separate text with theory from the code and results
   - Might have to copy/repeat text from the book in the notebooks to make them understandable (or vice-versa)
   - Still bad PR workflow for code
3. Use **Sphinx** with some useful plugins:
   
   Advantages:
   - It's the default documentation generation system for Python projects (including Fatiando). So there are a lot of plugins and people are familiar with it.
   - Can generate PDF, HTML and EPUB from the same source
   - Writing in reStructuredText (`.rst`) and `.py` files is PR friendly
   - Access to [(numbered) Latex equations](http://www.sphinx-doc.org/pt_BR/stable/ext/math.html) and hyperreferences
   - Bibtex citations using [sphinx natbib](http://wnielson.bitbucket.org/projects/sphinx-natbib/)
   - Test code in the book using [doctest syntax](http://www.sphinx-doc.org/pt_BR/stable/ext/doctest.html)
   - Code that [produces matplotlib plots](http://matplotlib.org/sampledoc/extensions.html#inserting-matplotlib-plots)
   - Sections with notebook-style text + code + images using [sphinx-gallery](http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py) (it also automatically generates a `.ipynb` file from the input `.py` or `.rst`)
   
   Disadvantages:
   - Would have to write sections with code in `.py` files (no interactivity during the development)
   - Can't use some rich-text Jupyter notebook features (widgets, embded videos, etc)
   - Would probably need to hack some plugins to do everything we want. But this can be done only when needed.
   - Will need to test if all the plugins above work well together (particularly sphinx-gallery and sphinx-natbib).

**My thoughts**: I tend toward using Sphinx. Support for a PR friendly workflow is a must if we are to write this together. Also, through some plugins we can get most of the advantages of notebooks. The code can be automatically tested on TravisCI. The generated notebook files can be automatically commited to a separate repository and used online with mybinder.

### PR DESCRIPTION
**Pull request by leouieda**
Fixes #1 

Make the lecture notes into a proper textbook (in English). 

The goal is to have a practical introduction to the topic of inverse problems, with lots of examples and code.

## Main features

* Python code to implement everything.
* Textbook in HTML and PDF formats (using sphinx).
* Examples implementations of inversions (formulate, implement, test, and run real examples).
* At least one geophysical example for every important point in the book. 
* Write tests for functions we implement and include them in the book. We use the tests ourselves and help enforce good software practices for readers. Win win.
* Short and concise.
* Accessible language and math.

## Developing the 2.0 version

We'll use this PR and the `2.0` branch as the basis for the new version. Only merge this PR when the 2.0 version is ready.

Test versions and major changes that need to be discussed can be implemented in separate branches and merged into `2.0` using a pull request.

Use issues to discuss ideas and planning.

### CODE REVIEW

**Comment by leouieda** [comment]
@birocoles I want to start work on this and setup the infrastructure (TravisCI, sphinx configuration, etc). Then we can try to work slowly when we get a chance, instead of having to do a whole lot of work just to get started.

**Comment by birocoles** [comment]
Nice @leouieda! Dou you now [DocOnce](http://hplgit.github.io/teamods/writing_reports/index.html)? I consider converting my class notes into a book by using DocOnce.

**Comment by leouieda** [comment]
Yeah I've seen it before. It looks promising but I've never used it before and I'm not sure what limitations it might have. It wouldn't be very nice to invest a lot of time on it and then come across something we can't do using it. Sphinx is more comfortable for me and it can generate all the formats that DocOnce can. Plus, I don't think you can run doctests from DocOnce but sphinx can.

**Comment by leouieda** [comment]
Have you tried it before?

**Comment by birocoles** [comment]
I have tried some simple examples. I have no problem in using Sphinx instead of DocOnce.

**Pull request closed without merging**
